### ISSUE TITLE
Website intermittently gives "500 Internal Server Error"

### ISSUE THREAD

**Issue by trivikr** [styfle/packagephobia#1033]
I'm trying to get publish and install size numbers for `aws-sdk`, and the website is returning "500 Internal Server Error".
It's consistently reproducible, but the error goes away after some time.

On quick read through [previous reports](https://github.com/styfle/packagephobia/issues?q=is%3Aissue+sort%3Aupdated-desc+%22500+Internal+Server+Error%22+is%3Aclosed) which mentioned "500 Internal Server Error", it appears to be an intermittent issue. But logging it for deep dive in future, if interested.

Example link: https://packagephobia.com/result?p=aws-sdk@2.1554.0

<details>
<summary>Screenshot</summary>

<img width="825" alt="packagephobia-aws-sdk-500-internal-server-error" src="https://github.com/styfle/packagephobia/assets/16024985/8c02f90a-78ba-4f1b-bf36-2b9f3da67133">

</details>

**Comment by styfle** [comment]
```
npm WARN tar TAR_ENTRY_ERROR ENOSPC: no space left on device, write
npm ERR! code ENOSPC
npm ERR! syscall write
npm ERR! errno -28
npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
```

This happens from time to time when concurrency is very high and we exceed 500MB disk limit.

Its fixed now when you visit https://packagephobia.com/result?p=aws-sdk

I believe visiting https://packagephobia.com/result?p=aws-sdk@2.1554.0 will continue to show an error since we cache errors for a couple days to avoid wasting compute (most failure are not disk space related).
