### ISSUE TITLE
Changing the label of the badge

### ISSUE THREAD

**Issue by jorgebucaran** [styfle/packagephobia#117]
Hi! @styfle 

Is it possible to change the text on the left side of the badge? e.g., "size" instead of "install size".

**Comment by styfle** [comment]
Hi Jorge, thanks for asking!

I originally went with "install size" because it differentiates itself from "publish size" or "gzip size".

At this time, there is now way to change this label.

However, I would be happy to accept a PR to add a new query string parameter (let's call it `label` to match https://badgen.net) if you are interested 😄

**Comment by jorgebucaran** [comment]
Thank you, @styfle! I think you are right and your word choice was the most reasonable one. I was just curious whether it was possible to change the text or not. I'll have a look at your code and see if I can do anything, but I can't promise I will. I am not too familiar with how shields/badges work, but it could be a fun learning experience.

Feel free to close here if this is not something you would like to track at this time.

Cheers! :)

**Comment by jorgebucaran** [comment]
@styfle Awesome! Lol I tried ?name=size and ?id=size before giving up. So close! 😃
