### ISSUE TITLE
Remove the version if the user/querystring did not specify version

### ISSUE THREAD

**Issue by styfle** [styfle/packagephobia#132]
If I type in [tape](https://packagephobia.now.sh/result?p=tape) without a version, the `latest` version is used.
This works great for displaying install size and such.

But it also fills out a version for all the generated links such as badge, npmjs.com, libraries.io, etc.

These links should not specify a version unless the user clicked on a version or typed in a version.

For example, visiting this page https://packagephobia.now.sh/result?p=tape should render the badge https://packagephobia.now.sh/badge?p=tape instead of https://packagephobia.now.sh/badge?p=tape@4.9.1

If the user visits https://packagephobia.now.sh/result?p=tape@4.9.1 then show the versioned badge https://packagephobia.now.sh/badge?p=tape@4.9.1

**Comment by ansballard** [comment]
So the issue here is that from `page-props.ts` on, there is always a name and version, because if version isn't specified, the latest is grabbed ([See here](https://github.com/styfle/packagephobia/blob/master/src/page-props/results.ts#L28)). My thought is to add a `showLatest` or `isLatest` or `ignoreVersion` flag at that point, which is then passed all the way down to the `LinkedLogos` component, where the links can optionally ignore the `version` field if the new flag is true.

Thoughts? If it goes that route it shouldn't be too complex, but I don't really like having an `isLatest` flag while also passing an explicit version, it feels a little dirty to me.

**Comment by styfle** [comment]
Yes, this is my immediate thought too which is why I haven't implemented it yet.
It feels a little messy.

I almost wanted to put the new flag on the `PkgSize` object but then that would get passed around everywhere and even sent out the API results which might be exposing too much.

**Comment by styfle** [comment]
Since we both came to the same conclusion (even though its not clean looking), I created a PR: #140
