### ISSUE TITLE
Compare the size of multiple packages

### ISSUE THREAD

**Issue by egoist** [styfle/packagephobia#133]
I'd like something like this to work!

<img width="622" alt="2018-09-11 12 48 30" src="https://user-images.githubusercontent.com/8784712/45338687-0874fb80-b5c1-11e8-88a6-626cbfabc9cc.png">

**Comment by styfle** [comment]
Yes this would be great!

I think we can extend this feature to upload `package.json` and read the dependencies from the file in order to match the behavior of https://bundlephobia.com/scan

For example, take a look at this result page: https://bundlephobia.com/scan-results?packages=react@16.4.2,react-dom@16.4.2,redis@2.8.0,semver@5.5.0

**Comment by zipang** [comment]
Yes, comparing several packages on the same page would really be a must !

**Comment by styfle** [comment]
Agreed! Anyone willing to create a PR?

**Comment by gokulkrishh** [comment]
@styfle I can create a PR for compare multiple packages. 

I have some initial idea. I will create a PR. Let me know if you have any more ideas to improve it.

**Comment by dasZGFz** [comment]
@styfle In the meantime, I used the api to make my own site crediting and linking back to yours. Hope that's ok 😓

https://github.com/dasZGFz/packagephobia-analyze

**Comment by styfle** [comment]
@dasZGFz That looks cool! Can you create a PR to turn this into the `/scan` page?

**Comment by dasZGFz** [comment]
@styfle I'll try to, not fancying the idea of converting my Svelte code to React 😱. Luckily there seems to be some adapters so I'll give it a go if I get the time to.
