### ISSUE TITLE
[Question] Is it able to provide install size for development and production respectively?

### ISSUE THREAD

**Issue by momocow** [styfle/packagephobia#134]
I'm making a simple plugin manager for my electron app, which consults `npms.io` with some proper filters to list related packages and metadatas from `package.json` for users.
Also, if there is a way to tell the user how much disk space is required (approximately) to perform the installation would be better.

In the document, it says

> This is useful for inspecting potential devDependencies without using up precious disk space or waiting minutes for npm install. Ain't nobody got time for dat.

If I don't misunderstand anything, the installation size currently reported by packagephobia is a development installation.
I'm wondering if it is able to provide the production installation size.

Thanks for your service anyway. 😃

**Comment by styfle** [comment]
Hi @momocow that's a good question!

I think there is a bit of confusion.

Package Phobia only reports production install sizes...it's identical to performing `npm install some-package` in a empty node project.

The reason why I wrote `devDependencies` is to avoid using the exact same tagline as https://bundlephobia.com which only shows the bundled sizes.

Typically, your `devDependencies` are going to be significantly larger than your `dependencies` and often, `dependencies` get bundled via webpack if they are for the front-end.

But of course, `dependencies` like `express` do not get bundled so these are appropriate for Package Phobia.

Really, the problem is that npm packages have no way of indicating they are browser-only besides putting something in the README so it's up to the person who is inspecting size to use the appropriate tool.

**Comment by momocow** [comment]
Thanks for your answer,
and it seems that packagephobia is actually what I need!
🎉

**Comment by styfle** [comment]
Yes, I should have summarized all of that by saying Package Phobia is the correct tool for your use case: Electron.

Also be sure to read this part of the readme: https://github.com/styfle/packagephobia#why-is-the-size-different-than-size-on-disk
