### ISSUE TITLE
[API] add support for dist-tags?

### ISSUE THREAD

**Issue by aleclarson** [styfle/packagephobia#191]
(eg: `latest`, `next`, etc)

```
https://packagephobia.now.sh/api.json?p=lodash@latest
```

The `dist-tags` are available from NPM's API.

**Comment by styfle** [comment]
I have thought about this a bit and never implemented because the caching mechanism would need to be different for dist-tags (because they can change).

Right now, the latest dist-tag is already supported by leaving of the `@latest`.

This seems like it would only be useful for `next` or `beta`.

Maybe the answer is to do a lookup to see which version that the dist-tag is pointing to.

So if the user types in `typescript@rc` we would "redirect" to `typescript@3.2.0-rc`.

![image](https://user-images.githubusercontent.com/229881/48629134-dac47e00-e986-11e8-8aac-778236de796f.png)

How does that sound?

**Comment by styfle** [comment]
Would you like to make a PR? 😄 😸 😃

**Comment by aleclarson** [comment]
Um, we'll see if I can find time next month. 😉

**Comment by styfle** [comment]
@aleclarson I created PR #192 

Can you give this a quick test and see if it looks correct? https://packagephobia-xkhcuituua.now.sh

**Comment by aleclarson** [comment]
Works perfectly! Thanks for taking care of it. :)

**Comment by styfle** [comment]
Great! Merged and deploying to prod now https://packagephobia.now.sh
