### ISSUE TITLE
Support npm install from git remote url

### ISSUE THREAD

**Issue by szmarczak** [styfle/packagephobia#211]
That's just an idea. Example: `got@master`

**Comment by styfle** [comment]
It's possible.

But currently, only code published to npm is available for Package Phobia because each version is permanently saved in redis. Since `master` is mutable, there would need to be a different retention policy. It also would require adding some special cases for version checking as well as reading 

I'm curious what the use-case is here?
Perhaps you would benefit from the [other similar tools in the readme](https://github.com/styfle/packagephobia#how-is-this-different) to add to your CI that could run each time `master` is pushed?

**Comment by szmarczak** [comment]
> I'm curious what the use-case is here?

Just to compare how the `master` changes affected the package size compared to the latest release :P Lots of stuff may be going on.

> Since master is mutable, there would need to be a different retention policy. It also would require adding some special cases for version checking as well as reading

I agree. Hmm, what about if it'd update every three days if the latest commit hash changes?

**Comment by styfle** [comment]
> Just to compare how the `master` changes affected the package size compared to the latest release :P Lots of stuff may be going on.

Wouldn't you want to catch that before it gets merged to master?

Perhaps a CI check with [size-limit](https://github.com/ai/size-limit#applications) (with webpack:false) or [bundlesize](https://github.com/siddharthkp/bundlesize#1-add-the-path-and-maxsize-in-your-packagejson) (with compression:none) might solve your problem.

Also, there is a request for multiple packages in #133 that could be used to solve this problem (with a small script that turns the runtime "dependencies" list from `package.json` into a url for package phobia although this isn't implemented yet).

Lastly, a simple solution to your problem is publish `master` to npm as a pre-release. For example, typescript publishes nightly as you can see here: https://packagephobia.now.sh/result?p=typescript@3.3.0-dev.20181121

**Comment by szmarczak** [comment]
Yeah, that would definitely solve the problem. But if I wanted to see another project that doesn't belong to me - it won't be easy.

**Comment by styfle** [comment]
What is the use case for checking the master branch of a project that you don't own?

The only way to add that project as a dependency is to install using the git remote url instead of by npm name which I don't believe is a very common way to do it.

```
npm install https://github.com/sindresorhus/got.git
```

Is this how you are installing dependencies?

**Comment by szmarczak** [comment]
> What is the use case for checking the master branch of a project that you don't own?

Curiosity. Some projects are under heavy development and have no new stable release for months. I just wanted to see how the changes affected the install size.

> Is this how you are installing dependencies?

How is this question related to the issue? Anyway, the answer is no.

**Comment by styfle** [comment]
Ok I think if this is implemented, it should support the full git remote url as defined in the [npm docs](https://docs.npmjs.com/cli/install) where the git remote url is defined as:

```
<protocol>://[<user>[:<password>]@]<hostname>[:<port>][:][/]<path>[#<commit-ish> | #semver:<semver>]
```

This allows any commit hash, not just master.

Would you like to submit a PR for this feature?

**Comment by szmarczak** [comment]
Yeah, sure. I'm glad I can help :)

**Comment by styfle** [comment]
Now that GitHub provides it's own package manager, there really isn't a need to read directly from git.

As noted in #388, `git` is not available at runtime and I don't intend on adding it anytime soon so I'll close this issue.

**Comment by szmarczak** [comment]
You're right: https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry

**Comment by szmarczak** [comment]
There should be a button to select the wanted registry (NPM/GitHub). Should I open another issue for this?

**Comment by styfle** [comment]
Yes, a new issue is best because its a different problem to solve.
