### ISSUE TITLE
500 error on certain packages

### ISSUE THREAD

**Issue by r0mflip** [styfle/packagephobia#218]
Having a look [mdx-deck](https://github.com/jxnblk/mdx-deck), I clearly wanted to know its absurd side on install. I queried on packagephobia.now.sh, the request takes some time and fails with a 500 error.

IDK but this is the only package that I know of has this problem. I came to realize that the mdx-deck (on a manual install) is around 570MB, with puppeteer, it's dependency weighing 513MB. Packagephobia results the size of puppeteer without any problem.

I don't understand way it fails. I've ran a local packagephobia and tried to look at errors but failed (Iam running windows currently, nothing works).

**Comment by styfle** [comment]
There's a timeout implemented in #56 that avoids bringing down the whole system for these massive packages. We currently get hundreds of requests per second (because of badges used everywhere) so after some timeout period, it gives up.

I just tried again and was able to achieve the correct install size.

[![install size](https://packagephobia.now.sh/badge?p=mdx-deck@1.8.2)](https://packagephobia.now.sh/result?p=mdx-deck@1.8.2)

This package has 855 dependencies, what an achievement! https://npm.anvaka.com/#/view/2d/mdx-deck

**Comment by r0mflip** [comment]
> I just tried again and was able to achieve the correct install size.

Wait, how?

**Comment by styfle** [comment]
It's hit or miss. The timeout is based on time, not on number of dependencies. So if the server can install it faster (maybe certain things get cached) the second time might work.

**Comment by r0mflip** [comment]
> Gaah.., just ran inside WSL. Puppeteer in Linux is apparently 200MB smaller.

Failed. My math is bad 🤦‍♂️

**Comment by styfle** [comment]
Yes this is a known limitation with native packages. They typically come out to different sizes depending on the OS. This is one of the reasons the puppeteer team didn't want to display the badge in [#2552](https://github.com/GoogleChrome/puppeteer/pull/2552).

Currently, Package Phobia runs in Alpine Linux so your size may vary. Also see the [readme#why-is-the-size-different-than-size-on-disk](https://github.com/styfle/packagephobia/blob/master/README.md#why-is-the-size-different-than-size-on-disk) for more info.
