### ISSUE TITLE
Incorrect badge redirect

### ISSUE THREAD

**Issue by jaydenseric** [styfle/packagephobia#241]
This is the generated markdown:

```md
[![install size](https://packagephobia.now.sh/badge?p=graphql-api-koa@2.0.0)](https://packagephobia.now.sh/result?p=graphql-api-koa@2.0.0)
```

But the badge redirects to this URL:

[https://badgen.now.sh/badge/install%20size/96.5%20kB/44CC11](https://badgen.now.sh/badge/install%20size/96.5%20kB/44CC11)

When it should go here:

[https://badgen.net/packagephobia/install/graphql-api-koa@2.0.0](https://badgen.net/packagephobia/install/graphql-api-koa@2.0.0)

**Comment by styfle** [comment]
Hi Jayden, thanks for pointing this out!

When badgen was first released, it was on a different domain and didn't have a /packagephobia route.

When @amio implemented the /packagephobia route in badgen, the algorithm differs slightly from the real Package Phobia.

Compare these two:

https://packagephobia.now.sh/result?p=webpack

https://badgen.net/packagephobia/install/webpack

Both the number of decimal places and (more importantly) the base is different (base 2 vs base 10 sometimes referred to as mebibytes vs megabytes).

So it wouldn't make sense to just swap out the badge right now with those differences.

I went with base 2 originally because it matched `du -sh node_modules` but maybe its time to switch to base 10?

**Comment by amio** [comment]
I thought [this](https://github.com/amio/badgen-service/blob/2e1b44c7039581c32f24bd005231c1d73007e960/libs/live-fns/packagephobia.js#L31-L34) would output same result as packagephobia 🤔

Is it possible to get same result using `byte-size` package?

**Comment by styfle** [comment]
@amio That should be about the same. Should I just return the byte size string in the API (and maybe the color)? That way you don't have to duplicate any of the logic?

**Comment by amio** [comment]
@styfle That would be nice!

**Comment by styfle** [comment]
@amio Does this get you everything you need? #266 

## Before

https://packagephobia-3z2a1ipbd.now.sh/api.json?p=express@4.16.1

## After

https://packagephobia-3z2a1ipbd.now.sh/v2/api.json?p=express@4.16.1

**Comment by amio** [comment]
Great! I'll update badgen soon.

**Comment by amio** [comment]
@styfle ping me when it's online ;-)

**Comment by styfle** [comment]
@amio It's ready!
