### ISSUE TITLE
Fails for parse-dashboard

### ISSUE THREAD

**Issue by alberto264** [styfle/packagephobia#408]
https://packagephobia.now.sh/result?p=parse-dashboard

Internal server error :(

**Comment by styfle** [comment]
That's because `parse-dashboard` has a dependency on a git branch instead of a npm version.

https://github.com/parse-community/parse-dashboard/blob/3e1939dcb9f8f99188de84ad951d3624184bd228/package.json#L40

Looks like it was added in this PR: https://github.com/parse-community/parse-dashboard/pull/1145
