### ISSUE TITLE
Add an option to exclude `@types/node` from package size

### ISSUE THREAD

**Issue by szmarczak** [styfle/packagephobia#512]
So the package size is more accurate for TypeScript users.

**Comment by styfle** [comment]
I don't understand. How would this be more accurate?

Can you give an example package that is incorrect?

**Comment by szmarczak** [comment]
> How would this be more accurate?

Because you only install `@types/node` only once, so when you use TypeScript for Node.js development you already have `@types/node` installed.

All the packages: `@types/keyv`, `@types/cacheable-request`, `@types/...` require `@types/node` to be installed, which itself weighs ~670KB. When you install `@types/keyv` + `@types/cacheable-request` you won't have doubled `@types/node`, there will be only one `@types/node` :)

> Can you give an example package that is incorrect?

I didn't say **incorrect**. I said **more accurate**.

**Comment by styfle** [comment]
I think what you are describing is called [deduping](https://npm.github.io/how-npm-works-docs/npm3/duplication.html) was was introduced in npm 3.

Basically, if package A and package B both depend on package C, then C is installed once instead of twice. It sounds like package C in your case is `@types/node`.

However, Package Phobia doesn't know which packages you already have installed on your machine so it can't perform deduping.
