### ISSUE TITLE
Command line package

### ISSUE THREAD

**Issue by Siilwyn** [styfle/packagephobia#88]
:thought_balloon: what do you think of creating a packagephobia CLI tool? Maybe it's possible to re-use core logic that checks the size for a server.

**Comment by Siilwyn** [comment]
Hi there @styfle,

my goal would be to run the CLI from a CI service to check the size of my own source code + node modules for pull requests. So when people add new dependencies in a PR I can check the size before merging.

**Comment by styfle** [comment]
Do you want this to be a function that would fail `npm test` (travis for example), or do you want it to run as a service to use with GitHub Checks like [Bundle Size](https://github.com/siddharthkp/bundlesize#2-build-status)?

**Comment by Siilwyn** [comment]
I think both are great, though the first one is simpler to build I think.

**Comment by styfle** [comment]
Ok, and my guess is that you want to take into account `.npmignore` so that those files/folders are ignored when checking the size?

For example, most people do not publish their `tests` folder to npm because consumers do not need it, so you likely do not want to check the size of that folder, correct?

**Comment by Siilwyn** [comment]
Sorry about the late reply, I was thinking of creating a PR but have to find some time first with all kinds of other projects. ^^

I would indeed ignore the files in `.npmignore` and only include the files in the array of package.json `files` key. The purpose for me would be to test the file size of the npm package on every commit.

**Comment by jimmywarting** [comment]
i would like to be able to upload a package.json as a file or url
everything is not a npm package and some are private

**Comment by styfle** [comment]
@jimmywarting Agreed. There is a feature request here: #133

**Comment by egoist** [comment]
https://github.com/egoist/npm-size

npm-size could probably suit your needs, I can add a `--size-limit <size>` flag for your use case.

**Comment by egoist** [comment]
<img width="529" alt="2019-01-31 5 21 19" src="https://user-images.githubusercontent.com/8784712/52044292-c3a42e00-257c-11e9-9d1d-016d885090ac.png">

`--limit` flag is available now

**Comment by styfle** [comment]
Closing this issue since `npm-size . --limit 3mb` solves this use case.

Another solution is to run `npm pack` and measure the size of the resulting tarball.

Also see CLI tools listed in the [How is this different?](https://github.com/styfle/packagephobia#how-is-this-different) section of the readme.
